/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as ApiPublicDemoLoginRouteImport } from './routes/api/public/demo-login'
import { Route as AuthenticatedProjectsIdIndexRouteImport } from './routes/_authenticated/projects.$id.index'
import { Route as AuthenticatedProjectsIdRepositoryRouteImport } from './routes/_authenticated/projects.$id.repository'
import { Route as AuthenticatedProjectsIdMembersRouteImport } from './routes/_authenticated/projects.$id.members'
import { Route as AuthenticatedProjectsIdHistoryRouteImport } from './routes/_authenticated/projects.$id.history'
import { Route as AuthenticatedProjectsIdDocsRouteImport } from './routes/_authenticated/projects.$id.docs'
import { Route as AuthenticatedProjectsIdChatRouteImport } from './routes/_authenticated/projects.$id.chat'
import { Route as AuthenticatedProjectsIdBlueprintRouteImport } from './routes/_authenticated/projects.$id.blueprint'
import { Route as AuthenticatedProjectsIdApprovalsRouteImport } from './routes/_authenticated/projects.$id.approvals'
import { Route as AuthenticatedProjectsIdAlignmentRouteImport } from './routes/_authenticated/projects.$id.alignment'
import { Route as ApiPublicProjectsIdGithubWebhookRouteImport } from './routes/api/public/projects.$id.github-webhook'
import { Route as ApiPublicProjectsIdDriftRouteImport } from './routes/api/public/projects.$id.drift'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDemoLoginRoute = ApiPublicDemoLoginRouteImport.update({
  id: '/api/public/demo-login',
  path: '/api/public/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdIndexRoute =
  AuthenticatedProjectsIdIndexRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRepositoryRoute =
  AuthenticatedProjectsIdRepositoryRouteImport.update({
    id: '/projects/$id/repository',
    path: '/projects/$id/repository',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdMembersRoute =
  AuthenticatedProjectsIdMembersRouteImport.update({
    id: '/projects/$id/members',
    path: '/projects/$id/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdHistoryRoute =
  AuthenticatedProjectsIdHistoryRouteImport.update({
    id: '/projects/$id/history',
    path: '/projects/$id/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdDocsRoute =
  AuthenticatedProjectsIdDocsRouteImport.update({
    id: '/projects/$id/docs',
    path: '/projects/$id/docs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdChatRoute =
  AuthenticatedProjectsIdChatRouteImport.update({
    id: '/projects/$id/chat',
    path: '/projects/$id/chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdBlueprintRoute =
  AuthenticatedProjectsIdBlueprintRouteImport.update({
    id: '/projects/$id/blueprint',
    path: '/projects/$id/blueprint',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdApprovalsRoute =
  AuthenticatedProjectsIdApprovalsRouteImport.update({
    id: '/projects/$id/approvals',
    path: '/projects/$id/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdAlignmentRoute =
  AuthenticatedProjectsIdAlignmentRouteImport.update({
    id: '/projects/$id/alignment',
    path: '/projects/$id/alignment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicProjectsIdGithubWebhookRoute =
  ApiPublicProjectsIdGithubWebhookRouteImport.update({
    id: '/api/public/projects/$id/github-webhook',
    path: '/api/public/projects/$id/github-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProjectsIdDriftRoute =
  ApiPublicProjectsIdDriftRouteImport.update({
    id: '/api/public/projects/$id/drift',
    path: '/api/public/projects/$id/drift',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/demo-login': typeof ApiPublicDemoLoginRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$id/alignment': typeof AuthenticatedProjectsIdAlignmentRoute
  '/projects/$id/approvals': typeof AuthenticatedProjectsIdApprovalsRoute
  '/projects/$id/blueprint': typeof AuthenticatedProjectsIdBlueprintRoute
  '/projects/$id/chat': typeof AuthenticatedProjectsIdChatRoute
  '/projects/$id/docs': typeof AuthenticatedProjectsIdDocsRoute
  '/projects/$id/history': typeof AuthenticatedProjectsIdHistoryRoute
  '/projects/$id/members': typeof AuthenticatedProjectsIdMembersRoute
  '/projects/$id/repository': typeof AuthenticatedProjectsIdRepositoryRoute
  '/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute
  '/api/public/projects/$id/drift': typeof ApiPublicProjectsIdDriftRoute
  '/api/public/projects/$id/github-webhook': typeof ApiPublicProjectsIdGithubWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/demo-login': typeof ApiPublicDemoLoginRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$id/alignment': typeof AuthenticatedProjectsIdAlignmentRoute
  '/projects/$id/approvals': typeof AuthenticatedProjectsIdApprovalsRoute
  '/projects/$id/blueprint': typeof AuthenticatedProjectsIdBlueprintRoute
  '/projects/$id/chat': typeof AuthenticatedProjectsIdChatRoute
  '/projects/$id/docs': typeof AuthenticatedProjectsIdDocsRoute
  '/projects/$id/history': typeof AuthenticatedProjectsIdHistoryRoute
  '/projects/$id/members': typeof AuthenticatedProjectsIdMembersRoute
  '/projects/$id/repository': typeof AuthenticatedProjectsIdRepositoryRoute
  '/projects/$id': typeof AuthenticatedProjectsIdIndexRoute
  '/api/public/projects/$id/drift': typeof ApiPublicProjectsIdDriftRoute
  '/api/public/projects/$id/github-webhook': typeof ApiPublicProjectsIdGithubWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/demo-login': typeof ApiPublicDemoLoginRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$id/alignment': typeof AuthenticatedProjectsIdAlignmentRoute
  '/_authenticated/projects/$id/approvals': typeof AuthenticatedProjectsIdApprovalsRoute
  '/_authenticated/projects/$id/blueprint': typeof AuthenticatedProjectsIdBlueprintRoute
  '/_authenticated/projects/$id/chat': typeof AuthenticatedProjectsIdChatRoute
  '/_authenticated/projects/$id/docs': typeof AuthenticatedProjectsIdDocsRoute
  '/_authenticated/projects/$id/history': typeof AuthenticatedProjectsIdHistoryRoute
  '/_authenticated/projects/$id/members': typeof AuthenticatedProjectsIdMembersRoute
  '/_authenticated/projects/$id/repository': typeof AuthenticatedProjectsIdRepositoryRoute
  '/_authenticated/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute
  '/api/public/projects/$id/drift': typeof ApiPublicProjectsIdDriftRoute
  '/api/public/projects/$id/github-webhook': typeof ApiPublicProjectsIdGithubWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/public/demo-login'
    | '/projects/'
    | '/projects/$id/alignment'
    | '/projects/$id/approvals'
    | '/projects/$id/blueprint'
    | '/projects/$id/chat'
    | '/projects/$id/docs'
    | '/projects/$id/history'
    | '/projects/$id/members'
    | '/projects/$id/repository'
    | '/projects/$id/'
    | '/api/public/projects/$id/drift'
    | '/api/public/projects/$id/github-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/public/demo-login'
    | '/projects'
    | '/projects/$id/alignment'
    | '/projects/$id/approvals'
    | '/projects/$id/blueprint'
    | '/projects/$id/chat'
    | '/projects/$id/docs'
    | '/projects/$id/history'
    | '/projects/$id/members'
    | '/projects/$id/repository'
    | '/projects/$id'
    | '/api/public/projects/$id/drift'
    | '/api/public/projects/$id/github-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/api/public/demo-login'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$id/alignment'
    | '/_authenticated/projects/$id/approvals'
    | '/_authenticated/projects/$id/blueprint'
    | '/_authenticated/projects/$id/chat'
    | '/_authenticated/projects/$id/docs'
    | '/_authenticated/projects/$id/history'
    | '/_authenticated/projects/$id/members'
    | '/_authenticated/projects/$id/repository'
    | '/_authenticated/projects/$id/'
    | '/api/public/projects/$id/drift'
    | '/api/public/projects/$id/github-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDemoLoginRoute: typeof ApiPublicDemoLoginRoute
  ApiPublicProjectsIdDriftRoute: typeof ApiPublicProjectsIdDriftRoute
  ApiPublicProjectsIdGithubWebhookRoute: typeof ApiPublicProjectsIdGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/demo-login': {
      id: '/api/public/demo-login'
      path: '/api/public/demo-login'
      fullPath: '/api/public/demo-login'
      preLoaderRoute: typeof ApiPublicDemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id/': {
      id: '/_authenticated/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof AuthenticatedProjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/repository': {
      id: '/_authenticated/projects/$id/repository'
      path: '/projects/$id/repository'
      fullPath: '/projects/$id/repository'
      preLoaderRoute: typeof AuthenticatedProjectsIdRepositoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/members': {
      id: '/_authenticated/projects/$id/members'
      path: '/projects/$id/members'
      fullPath: '/projects/$id/members'
      preLoaderRoute: typeof AuthenticatedProjectsIdMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/history': {
      id: '/_authenticated/projects/$id/history'
      path: '/projects/$id/history'
      fullPath: '/projects/$id/history'
      preLoaderRoute: typeof AuthenticatedProjectsIdHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/docs': {
      id: '/_authenticated/projects/$id/docs'
      path: '/projects/$id/docs'
      fullPath: '/projects/$id/docs'
      preLoaderRoute: typeof AuthenticatedProjectsIdDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/chat': {
      id: '/_authenticated/projects/$id/chat'
      path: '/projects/$id/chat'
      fullPath: '/projects/$id/chat'
      preLoaderRoute: typeof AuthenticatedProjectsIdChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/blueprint': {
      id: '/_authenticated/projects/$id/blueprint'
      path: '/projects/$id/blueprint'
      fullPath: '/projects/$id/blueprint'
      preLoaderRoute: typeof AuthenticatedProjectsIdBlueprintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/approvals': {
      id: '/_authenticated/projects/$id/approvals'
      path: '/projects/$id/approvals'
      fullPath: '/projects/$id/approvals'
      preLoaderRoute: typeof AuthenticatedProjectsIdApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/alignment': {
      id: '/_authenticated/projects/$id/alignment'
      path: '/projects/$id/alignment'
      fullPath: '/projects/$id/alignment'
      preLoaderRoute: typeof AuthenticatedProjectsIdAlignmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/projects/$id/github-webhook': {
      id: '/api/public/projects/$id/github-webhook'
      path: '/api/public/projects/$id/github-webhook'
      fullPath: '/api/public/projects/$id/github-webhook'
      preLoaderRoute: typeof ApiPublicProjectsIdGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/projects/$id/drift': {
      id: '/api/public/projects/$id/drift'
      path: '/api/public/projects/$id/drift'
      fullPath: '/api/public/projects/$id/drift'
      preLoaderRoute: typeof ApiPublicProjectsIdDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsIdAlignmentRoute: typeof AuthenticatedProjectsIdAlignmentRoute
  AuthenticatedProjectsIdApprovalsRoute: typeof AuthenticatedProjectsIdApprovalsRoute
  AuthenticatedProjectsIdBlueprintRoute: typeof AuthenticatedProjectsIdBlueprintRoute
  AuthenticatedProjectsIdChatRoute: typeof AuthenticatedProjectsIdChatRoute
  AuthenticatedProjectsIdDocsRoute: typeof AuthenticatedProjectsIdDocsRoute
  AuthenticatedProjectsIdHistoryRoute: typeof AuthenticatedProjectsIdHistoryRoute
  AuthenticatedProjectsIdMembersRoute: typeof AuthenticatedProjectsIdMembersRoute
  AuthenticatedProjectsIdRepositoryRoute: typeof AuthenticatedProjectsIdRepositoryRoute
  AuthenticatedProjectsIdIndexRoute: typeof AuthenticatedProjectsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsIdAlignmentRoute: AuthenticatedProjectsIdAlignmentRoute,
  AuthenticatedProjectsIdApprovalsRoute: AuthenticatedProjectsIdApprovalsRoute,
  AuthenticatedProjectsIdBlueprintRoute: AuthenticatedProjectsIdBlueprintRoute,
  AuthenticatedProjectsIdChatRoute: AuthenticatedProjectsIdChatRoute,
  AuthenticatedProjectsIdDocsRoute: AuthenticatedProjectsIdDocsRoute,
  AuthenticatedProjectsIdHistoryRoute: AuthenticatedProjectsIdHistoryRoute,
  AuthenticatedProjectsIdMembersRoute: AuthenticatedProjectsIdMembersRoute,
  AuthenticatedProjectsIdRepositoryRoute:
    AuthenticatedProjectsIdRepositoryRoute,
  AuthenticatedProjectsIdIndexRoute: AuthenticatedProjectsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDemoLoginRoute: ApiPublicDemoLoginRoute,
  ApiPublicProjectsIdDriftRoute: ApiPublicProjectsIdDriftRoute,
  ApiPublicProjectsIdGithubWebhookRoute: ApiPublicProjectsIdGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
